### ISSUE TITLE
Document existing behavior concerning work nesting

### ISSUE THREAD

**Issue by JulieWinchester** [RepoCamp/Duke-B#5]
Describe current work nesting behavior on model and UI levels

**Comment by JocelynTriplett** [comment]
Useful methods:
:member_of - tells you the parent of the object
:members - tells you the children of the object
:member_ids - ids of the children

**Comment by JocelynTriplett** [comment]
Fedora for a parent record - 
ns006: 	hasMember
	http://127.0.0.1:8984/rest/dev/bv/73/c0/40/bv73c0402 <----- Image Work (child)
	http://127.0.0.1:8984/rest/dev/n0/09/w2/28/n009w228g <----- File attachment

Solr for a parent record:
"member_ids_ssim":["n009w228g",
          "bv73c0402"], (file attachment, child work)
 "file_set_ids_ssim":["n009w228g",
          "bv73c0402"],
