### ISSUE TITLE
Document current work nesting breadcrumb behavior in UI

### ISSUE THREAD

**Issue by JulieWinchester** [RepoCamp/Duke-B#7]

**Comment by JulieWinchester** [comment]
**UI nesting (adding nested relationships) behavior** 

* On the Works show page, there is an "Attach Child" button which allows one to add a new work as a child of the current work

* On the Works edit page, there is an "Other Works In This Work" section. This section does not appear on the new work page, although maybe it should. Things one can do here include:

  * Find a child work (searching for a work to add)
  * Deposit a new work as a child of this work
  * List current child works

**Comment by JulieWinchester** [comment]
**UI display behavior when you have works nested within each other**

* A parent work show page shows the first-level child work in the Items section
* A parent work edit page shows the first-level child in the "Other Works In This Work" section
* A child work show page gives no indication of the parent work?
* A child work edit page gives no indication of the parent work?

**Comment by JocelynTriplett** [comment]
Useful methods:
- :member_of tells you the parent of the object
- :members tells you the children of the object
